//
// Generated file, do not edit! Created by opp_msgtool 6.1 from NetworkMessages.msg.
//

#ifndef __NETWORKMESSAGES_M_H
#define __NETWORKMESSAGES_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0601
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class NetworkMsg;
class ReadRequestMsg;
class ReadResponseMsg;
class WriteRequestMsg;
class WriteResponseMsg;
class WritePropagationMsg;
class HeartbeatMsg;
class MissingWritesRequestMsg;
// cplusplus {{
#include <map>
#include <set>
#include <string>
typedef std::map<int, int> VectorClock;
typedef std::map<std::string, int> Store;
typedef std::map<int, std::set<int>> Writes;
// }}

/**
 * Class generated from <tt>NetworkMessages.msg:29</tt> by opp_msgtool.
 * <pre>
 * message NetworkMsg
 * {
 *     int sourceId;
 * }
 * </pre>
 */
class NetworkMsg : public ::omnetpp::cMessage
{
  protected:
    int sourceId = 0;

  private:
    void copy(const NetworkMsg& other);

  protected:
    bool operator==(const NetworkMsg&) = delete;

  public:
    NetworkMsg(const char *name=nullptr, short kind=0);
    NetworkMsg(const NetworkMsg& other);
    virtual ~NetworkMsg();
    NetworkMsg& operator=(const NetworkMsg& other);
    virtual NetworkMsg *dup() const override {return new NetworkMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getSourceId() const;
    virtual void setSourceId(int sourceId);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const NetworkMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, NetworkMsg& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>NetworkMessages.msg:33</tt> by opp_msgtool.
 * <pre>
 * message ReadRequestMsg extends NetworkMsg
 * {
 *     string key;
 * }
 * </pre>
 */
class ReadRequestMsg : public ::NetworkMsg
{
  protected:
    omnetpp::opp_string key;

  private:
    void copy(const ReadRequestMsg& other);

  protected:
    bool operator==(const ReadRequestMsg&) = delete;

  public:
    ReadRequestMsg(const char *name=nullptr, short kind=0);
    ReadRequestMsg(const ReadRequestMsg& other);
    virtual ~ReadRequestMsg();
    ReadRequestMsg& operator=(const ReadRequestMsg& other);
    virtual ReadRequestMsg *dup() const override {return new ReadRequestMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getKey() const;
    virtual void setKey(const char * key);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ReadRequestMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ReadRequestMsg& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>NetworkMessages.msg:37</tt> by opp_msgtool.
 * <pre>
 * message ReadResponseMsg extends NetworkMsg
 * {
 *     string key;
 *     int value;
 * }
 * </pre>
 */
class ReadResponseMsg : public ::NetworkMsg
{
  protected:
    omnetpp::opp_string key;
    int value = 0;

  private:
    void copy(const ReadResponseMsg& other);

  protected:
    bool operator==(const ReadResponseMsg&) = delete;

  public:
    ReadResponseMsg(const char *name=nullptr, short kind=0);
    ReadResponseMsg(const ReadResponseMsg& other);
    virtual ~ReadResponseMsg();
    ReadResponseMsg& operator=(const ReadResponseMsg& other);
    virtual ReadResponseMsg *dup() const override {return new ReadResponseMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getKey() const;
    virtual void setKey(const char * key);

    virtual int getValue() const;
    virtual void setValue(int value);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ReadResponseMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ReadResponseMsg& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>NetworkMessages.msg:42</tt> by opp_msgtool.
 * <pre>
 * message WriteRequestMsg extends NetworkMsg
 * {
 *     string key;
 *     int value;
 * }
 * </pre>
 */
class WriteRequestMsg : public ::NetworkMsg
{
  protected:
    omnetpp::opp_string key;
    int value = 0;

  private:
    void copy(const WriteRequestMsg& other);

  protected:
    bool operator==(const WriteRequestMsg&) = delete;

  public:
    WriteRequestMsg(const char *name=nullptr, short kind=0);
    WriteRequestMsg(const WriteRequestMsg& other);
    virtual ~WriteRequestMsg();
    WriteRequestMsg& operator=(const WriteRequestMsg& other);
    virtual WriteRequestMsg *dup() const override {return new WriteRequestMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getKey() const;
    virtual void setKey(const char * key);

    virtual int getValue() const;
    virtual void setValue(int value);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const WriteRequestMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, WriteRequestMsg& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>NetworkMessages.msg:47</tt> by opp_msgtool.
 * <pre>
 * message WriteResponseMsg extends NetworkMsg
 * {
 *     string key;
 * }
 * </pre>
 */
class WriteResponseMsg : public ::NetworkMsg
{
  protected:
    omnetpp::opp_string key;

  private:
    void copy(const WriteResponseMsg& other);

  protected:
    bool operator==(const WriteResponseMsg&) = delete;

  public:
    WriteResponseMsg(const char *name=nullptr, short kind=0);
    WriteResponseMsg(const WriteResponseMsg& other);
    virtual ~WriteResponseMsg();
    WriteResponseMsg& operator=(const WriteResponseMsg& other);
    virtual WriteResponseMsg *dup() const override {return new WriteResponseMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getKey() const;
    virtual void setKey(const char * key);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const WriteResponseMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, WriteResponseMsg& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>NetworkMessages.msg:51</tt> by opp_msgtool.
 * <pre>
 * message WritePropagationMsg extends NetworkMsg
 * {
 *     string key;
 *     int value;
 *     VectorClock vectorClock;
 * }
 * </pre>
 */
class WritePropagationMsg : public ::NetworkMsg
{
  protected:
    omnetpp::opp_string key;
    int value = 0;
    VectorClock vectorClock;

  private:
    void copy(const WritePropagationMsg& other);

  protected:
    bool operator==(const WritePropagationMsg&) = delete;

  public:
    WritePropagationMsg(const char *name=nullptr, short kind=0);
    WritePropagationMsg(const WritePropagationMsg& other);
    virtual ~WritePropagationMsg();
    WritePropagationMsg& operator=(const WritePropagationMsg& other);
    virtual WritePropagationMsg *dup() const override {return new WritePropagationMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getKey() const;
    virtual void setKey(const char * key);

    virtual int getValue() const;
    virtual void setValue(int value);

    virtual const VectorClock& getVectorClock() const;
    virtual VectorClock& getVectorClockForUpdate() { return const_cast<VectorClock&>(const_cast<WritePropagationMsg*>(this)->getVectorClock());}
    virtual void setVectorClock(const VectorClock& vectorClock);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const WritePropagationMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, WritePropagationMsg& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>NetworkMessages.msg:57</tt> by opp_msgtool.
 * <pre>
 * message HeartbeatMsg extends NetworkMsg
 * {
 *     simtime_t timestamp;
 *     VectorClock vectorClock;
 * }
 * </pre>
 */
class HeartbeatMsg : public ::NetworkMsg
{
  protected:
    omnetpp::simtime_t timestamp = SIMTIME_ZERO;
    VectorClock vectorClock;

  private:
    void copy(const HeartbeatMsg& other);

  protected:
    bool operator==(const HeartbeatMsg&) = delete;

  public:
    HeartbeatMsg(const char *name=nullptr, short kind=0);
    HeartbeatMsg(const HeartbeatMsg& other);
    virtual ~HeartbeatMsg();
    HeartbeatMsg& operator=(const HeartbeatMsg& other);
    virtual HeartbeatMsg *dup() const override {return new HeartbeatMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual omnetpp::simtime_t getTimestamp() const;
    virtual void setTimestamp(omnetpp::simtime_t timestamp);

    virtual const VectorClock& getVectorClock() const;
    virtual VectorClock& getVectorClockForUpdate() { return const_cast<VectorClock&>(const_cast<HeartbeatMsg*>(this)->getVectorClock());}
    virtual void setVectorClock(const VectorClock& vectorClock);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const HeartbeatMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, HeartbeatMsg& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>NetworkMessages.msg:62</tt> by opp_msgtool.
 * <pre>
 * message MissingWritesRequestMsg extends NetworkMsg
 * {
 *     Writes missingWrites;
 * }
 * </pre>
 */
class MissingWritesRequestMsg : public ::NetworkMsg
{
  protected:
    Writes missingWrites;

  private:
    void copy(const MissingWritesRequestMsg& other);

  protected:
    bool operator==(const MissingWritesRequestMsg&) = delete;

  public:
    MissingWritesRequestMsg(const char *name=nullptr, short kind=0);
    MissingWritesRequestMsg(const MissingWritesRequestMsg& other);
    virtual ~MissingWritesRequestMsg();
    MissingWritesRequestMsg& operator=(const MissingWritesRequestMsg& other);
    virtual MissingWritesRequestMsg *dup() const override {return new MissingWritesRequestMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const Writes& getMissingWrites() const;
    virtual Writes& getMissingWritesForUpdate() { return const_cast<Writes&>(const_cast<MissingWritesRequestMsg*>(this)->getMissingWrites());}
    virtual void setMissingWrites(const Writes& missingWrites);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const MissingWritesRequestMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, MissingWritesRequestMsg& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

inline any_ptr toAnyPtr(const VectorClock *p) {if (auto obj = as_cObject(p)) return any_ptr(obj); else return any_ptr(p);}
template<> inline VectorClock *fromAnyPtr(any_ptr ptr) { return ptr.get<VectorClock>(); }
inline any_ptr toAnyPtr(const Store *p) {if (auto obj = as_cObject(p)) return any_ptr(obj); else return any_ptr(p);}
template<> inline Store *fromAnyPtr(any_ptr ptr) { return ptr.get<Store>(); }
inline any_ptr toAnyPtr(const Writes *p) {if (auto obj = as_cObject(p)) return any_ptr(obj); else return any_ptr(p);}
template<> inline Writes *fromAnyPtr(any_ptr ptr) { return ptr.get<Writes>(); }
template<> inline NetworkMsg *fromAnyPtr(any_ptr ptr) { return check_and_cast<NetworkMsg*>(ptr.get<cObject>()); }
template<> inline ReadRequestMsg *fromAnyPtr(any_ptr ptr) { return check_and_cast<ReadRequestMsg*>(ptr.get<cObject>()); }
template<> inline ReadResponseMsg *fromAnyPtr(any_ptr ptr) { return check_and_cast<ReadResponseMsg*>(ptr.get<cObject>()); }
template<> inline WriteRequestMsg *fromAnyPtr(any_ptr ptr) { return check_and_cast<WriteRequestMsg*>(ptr.get<cObject>()); }
template<> inline WriteResponseMsg *fromAnyPtr(any_ptr ptr) { return check_and_cast<WriteResponseMsg*>(ptr.get<cObject>()); }
template<> inline WritePropagationMsg *fromAnyPtr(any_ptr ptr) { return check_and_cast<WritePropagationMsg*>(ptr.get<cObject>()); }
template<> inline HeartbeatMsg *fromAnyPtr(any_ptr ptr) { return check_and_cast<HeartbeatMsg*>(ptr.get<cObject>()); }
template<> inline MissingWritesRequestMsg *fromAnyPtr(any_ptr ptr) { return check_and_cast<MissingWritesRequestMsg*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __NETWORKMESSAGES_M_H

